workspace:
  base: /go
  path: src/github.com/AckeeDevOps/vaultier


pipeline:

  fetch:
    image: docker:git
    commands:
      - git fetch --tags
  
  test:
    image: golang:latest
    commands:
      - go test $(go list ./... | grep -v /vendor/) -v -cover
  
  lint:
    image: golang:latest
    commands:
      - go get -u golang.org/x/lint/golint
      - golint -set_exit_status . config client
  
  release:
    when:
      event:
        - tag
    image: golang:latest
    secrets: [github_token]
    commands:
      - curl -sL https://git.io/goreleaser | bash
